# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e61ed2b560298a1a44c18c87fd785254"
application_url = "https://blvd-interested-eagles-achievement.trycloudflare.com"
embedded = true
name = "nextapp-tst"
handle = "nextapp-tst"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "gitspark-perfumez-demo.myshopify.com"

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://blvd-interested-eagles-achievement.trycloudflare.com/auth/callback",
  "https://blvd-interested-eagles-achievement.trycloudflare.com/auth/shopify/callback",
  "https://blvd-interested-eagles-achievement.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
